### ISSUE TITLE
Error while launching panda_world.launch

### ISSUE THREAD

**Issue by apandastider** [justagist/panda_simulator#62]
I am getting the error **SetModelConfiguration service failed. Exiting.** after I am trying to launch the panda_world.launch file. My device is Ubuntu 18.04 and I am using Gazebo9 in ROS Melodic. 

Can anyone please guide me on how I can solve this problem? 

Thank you.

**Comment by apandastider** [comment]
[rospy.client][INFO] 2021-12-17 17:31:00,130: init_node, name[/robot_description], pid[7436]
[xmlrpc][INFO] 2021-12-17 17:31:00,130: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-17 17:31:00,131: Started XML-RPC server [http://apanrtx:34075/]
[rospy.init][INFO] 2021-12-17 17:31:00,131: ROS Slave URI: [http://apanrtx:34075/]
[rospy.impl.masterslave][INFO] 2021-12-17 17:31:00,131: _ready: http://apanrtx:34075/
[xmlrpc][INFO] 2021-12-17 17:31:00,131: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-12-17 17:31:00,132: Registering with master node http://localhost:11311
[rospy.init][INFO] 2021-12-17 17:31:00,231: registered with master
[rospy.rosout][INFO] 2021-12-17 17:31:00,232: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-17 17:31:00,234: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-17 17:31:00,234: initializing /clock core topic
[rospy.simtime][INFO] 2021-12-17 17:31:00,236: connected to core topic /clock
[rosout][INFO] 2021-12-17 17:31:00,238: Loading model XML from ros parameter robot_description
[rosout][INFO] 2021-12-17 17:31:00,250: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2021-12-17 17:31:00,510: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-12-17 17:31:02,253: topic[/clock] adding connection to [http://apanrtx:35529/], count 0
[rosout][INFO] 2021-12-17 17:31:02,363: Calling service /gazebo/spawn_urdf_model
[rosout][INFO] 2021-12-17 17:31:02,639: Spawn status: SpawnModel: Successfully spawned entity
[rosout][INFO] 2021-12-17 17:31:02,640: Waiting for service /gazebo/set_model_configuration
[rosout][INFO] 2021-12-17 17:31:02,644: temporary hack to **fix** the -J joint position option (issue #93), sleeping for 1 second to avoid race condition.
[rospy.internal][WARNING] 2021-12-17 17:31:02,955: Unknown error initiating TCP/IP socket to apanrtx:44733 (http://apanrtx:35529/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2021-12-17 17:31:02,956: topic[/clock] removing connection to http://apanrtx:35529/
[rosout][INFO] 2021-12-17 17:31:03,647: Calling service /gazebo/set_model_configuration
[rospy.internal][WARNING] 2021-12-17 17:31:03,652: Unknown error initiating TCP/IP socket to apanrtx:44733 (rosrpc://apanrtx:44733): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rosout][ERROR] 2021-12-17 17:31:03,652: SetModelConfiguration service failed. Exiting.
[rospy.core][INFO] 2021-12-17 17:31:03,655: signal_shutdown [atexit]
[rospy.internal][INFO] 2021-12-17 17:31:03,658: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2021-12-17 17:31:03,658: atexit
