### ISSUE TITLE
Controller registration fail: This controller requires a hardware interface of type 'panda_hardware_interface::SharedJointInterface'. Make sure this is registered in the hardware_interface::RobotHW class

### ISSUE THREAD

**Issue by ghost** [justagist/panda_simulator#64]
I have integrated a Franka Emika Panda on a Clearpath Ridgeback. The simulation for Panda in this package works fine for me when run alone but does not work when integrated with the ridgeback robot. 

I updated your `franka_panda_description` [here](https://github.com/justagist/franka_panda_description/blob/master/robots/panda_arm_hand.urdf.xacro) to  a macro and included it in my original URDF for the Ridgeback and other accessories file. Here is the code for that: 

```xml
      <!-- Arm(for simulated robot) -->
      <xacro:if value="$(optenv RIDGEBACK_SIM)">
        <xacro:if value="$(optenv RIDGEBACK_PANDA 0)"> 
          <xacro:include filename="$(find mbs_rp_description)/xacro/accessories/panda_arm/panda_arm_sim.urdf.xacro"/> 
          <xacro:panda_arm robot_name="panda" load_gripper="false" load_gazebo="true" use_gazebo_control="false" connected_to="$(arg connected_to)"/>
        </xacro:if>
      </xacro:if>
```

This URDF works fine and I confirmed it with testing different parameters and it works fine.

After this I have included [this](https://github.com/justagist/panda_simulator/blob/noetic-devel/panda_gazebo/launch/panda_world.launch) by removing `Gazebo launch include, robot_desription and URDF spawner for Gazebo` and left all the default controllers as it is. 

Now I have errors and the panda controllers are not launched probperly. Please have a look at the log below: 

```xml
... logging to /home/mbs/.ros/log/ad088a06-6d59-11ec-9d30-3d63d0be0631/roslaunch-Development-67726.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Development:41123/

SUMMARY
========

PARAMETERS
 * /SIMULATOR_: True
 * /arm/gravity_tip_name: panda_link8
 * /arm/root_name: panda_link0
 * /arm/tip_name: panda_link8
 * /controllers_config/default_controller: panda_simulator/p...
 * /controllers_config/position_controller: panda_simulator/p...
 * /controllers_config/torque_controller: panda_simulator/e...
 * /controllers_config/velocity_controller: panda_simulator/v...
 * /ekf_localization/base_link_frame: base_link
 * /ekf_localization/frequency: 50
 * /ekf_localization/imu0: /imu/data
 * /ekf_localization/imu0_config: [False, False, Fa...
 * /ekf_localization/imu0_differential: False
 * /ekf_localization/odom0: /ridgeback_veloci...
 * /ekf_localization/odom0_config: [False, False, Fa...
 * /ekf_localization/odom0_differential: False
 * /ekf_localization/odom_frame: odom
 * /ekf_localization/two_d_mode: True
 * /ekf_localization/world_frame: odom
 * /gazebo/enable_ros_network: True
 * /gazebo_ros_control/pid_gains/front_left_wheel/d: 0
 * /gazebo_ros_control/pid_gains/front_left_wheel/i: 0.1
 * /gazebo_ros_control/pid_gains/front_left_wheel/p: 1
 * /gazebo_ros_control/pid_gains/front_right_wheel/d: 0
 * /gazebo_ros_control/pid_gains/front_right_wheel/i: 0.1
 * /gazebo_ros_control/pid_gains/front_right_wheel/p: 1
 * /gazebo_ros_control/pid_gains/rear_left_wheel/d: 0
 * /gazebo_ros_control/pid_gains/rear_left_wheel/i: 0.1
 * /gazebo_ros_control/pid_gains/rear_left_wheel/p: 1
 * /gazebo_ros_control/pid_gains/rear_right_wheel/d: 0
 * /gazebo_ros_control/pid_gains/rear_right_wheel/i: 0.1
 * /gazebo_ros_control/pid_gains/rear_right_wheel/p: 1
 * /gripper_config/default_grasp_epsilon/inner: 0.005
 * /gripper_config/default_grasp_epsilon/outer: 0.005
 * /gripper_config/default_speed: 0.1
 * /gripper_config/joint_names: ['panda_finger_jo...
 * /lift_joint_position_controller/gains/d: 0
 * /lift_joint_position_controller/gains/i: 0.1
 * /lift_joint_position_controller/gains/p: 1
 * /lift_joint_position_controller/joint: mbs_lift_joint
 * /lift_joint_position_controller/type: position_controll...
 * /lift_joint_state_controller/publish_rate: 50
 * /lift_joint_state_controller/type: joint_state_contr...
 * /panda_simulator/effort_joint_gravity_controller/joints/panda_joint1_controller/joint: panda_joint1
 * /panda_simulator/effort_joint_gravity_controller/joints/panda_joint2_controller/joint: panda_joint2
 * /panda_simulator/effort_joint_gravity_controller/joints/panda_joint3_controller/joint: panda_joint3
 * /panda_simulator/effort_joint_gravity_controller/joints/panda_joint4_controller/joint: panda_joint4
 * /panda_simulator/effort_joint_gravity_controller/joints/panda_joint5_controller/joint: panda_joint5
 * /panda_simulator/effort_joint_gravity_controller/joints/panda_joint6_controller/joint: panda_joint6
 * /panda_simulator/effort_joint_gravity_controller/joints/panda_joint7_controller/joint: panda_joint7
 * /panda_simulator/effort_joint_gravity_controller/type: panda_sim_control...
 * /panda_simulator/effort_joint_torque_controller/joints/panda_joint1_controller/joint: panda_joint1
 * /panda_simulator/effort_joint_torque_controller/joints/panda_joint2_controller/joint: panda_joint2
 * /panda_simulator/effort_joint_torque_controller/joints/panda_joint3_controller/joint: panda_joint3
 * /panda_simulator/effort_joint_torque_controller/joints/panda_joint4_controller/joint: panda_joint4
 * /panda_simulator/effort_joint_torque_controller/joints/panda_joint5_controller/joint: panda_joint5
 * /panda_simulator/effort_joint_torque_controller/joints/panda_joint6_controller/joint: panda_joint6
 * /panda_simulator/effort_joint_torque_controller/joints/panda_joint7_controller/joint: panda_joint7
 * /panda_simulator/effort_joint_torque_controller/topic: /panda_simulator/...
 * /panda_simulator/effort_joint_torque_controller/type: panda_sim_control...
 * /panda_simulator/joint_state_controller/publish_rate: 100
 * /panda_simulator/joint_state_controller/type: joint_state_contr...
 * /panda_simulator/position_joint_position_controller/joints/panda_joint1_controller/joint: panda_joint1
 * /panda_simulator/position_joint_position_controller/joints/panda_joint1_controller/pid/d: 25.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint1_controller/pid/i: 10.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint1_controller/pid/p: 3000
 * /panda_simulator/position_joint_position_controller/joints/panda_joint2_controller/joint: panda_joint2
 * /panda_simulator/position_joint_position_controller/joints/panda_joint2_controller/pid/d: 30.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint2_controller/pid/i: 10.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint2_controller/pid/p: 3000
 * /panda_simulator/position_joint_position_controller/joints/panda_joint3_controller/joint: panda_joint3
 * /panda_simulator/position_joint_position_controller/joints/panda_joint3_controller/pid/d: 30.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint3_controller/pid/i: 10.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint3_controller/pid/p: 3000
 * /panda_simulator/position_joint_position_controller/joints/panda_joint4_controller/joint: panda_joint4
 * /panda_simulator/position_joint_position_controller/joints/panda_joint4_controller/pid/d: 50.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint4_controller/pid/i: 10.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint4_controller/pid/p: 3000
 * /panda_simulator/position_joint_position_controller/joints/panda_joint5_controller/joint: panda_joint5
 * /panda_simulator/position_joint_position_controller/joints/panda_joint5_controller/pid/d: 8.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint5_controller/pid/i: 10.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint5_controller/pid/p: 3000
 * /panda_simulator/position_joint_position_controller/joints/panda_joint6_controller/joint: panda_joint6
 * /panda_simulator/position_joint_position_controller/joints/panda_joint6_controller/pid/d: 5.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint6_controller/pid/i: 1.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint6_controller/pid/p: 3000
 * /panda_simulator/position_joint_position_controller/joints/panda_joint7_controller/joint: panda_joint7
 * /panda_simulator/position_joint_position_controller/joints/panda_joint7_controller/pid/d: 4.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint7_controller/pid/i: 10.0
 * /panda_simulator/position_joint_position_controller/joints/panda_joint7_controller/pid/p: 3000
 * /panda_simulator/position_joint_position_controller/topic_joint_command: /panda_simulator/...
 * /panda_simulator/position_joint_position_controller/topic_set_speed_ratio: /panda_simulator/...
 * /panda_simulator/position_joint_position_controller/type: panda_sim_control...
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint1_controller/joint: panda_joint1
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint1_controller/pid/d: 0.1
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint1_controller/pid/i: 0.0
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint1_controller/pid/p: 10
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint2_controller/joint: panda_joint2
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint2_controller/pid/d: 0.1
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint2_controller/pid/i: 1.0
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint2_controller/pid/p: 100
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint3_controller/joint: panda_joint3
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint3_controller/pid/d: 0.01
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint3_controller/pid/i: 0.0
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint3_controller/pid/p: 0.05
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint4_controller/joint: panda_joint4
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint4_controller/pid/d: 0.1
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint4_controller/pid/i: 0.01
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint4_controller/pid/p: 0.5
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint5_controller/joint: panda_joint5
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint5_controller/pid/d: 0.01
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint5_controller/pid/i: 0.0
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint5_controller/pid/p: 1.0
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint6_controller/joint: panda_joint6
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint6_controller/pid/d: 0.01
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint6_controller/pid/i: 0.0
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint6_controller/pid/p: 0.05
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint7_controller/joint: panda_joint7
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint7_controller/pid/d: 0.01
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint7_controller/pid/i: 0.0
 * /panda_simulator/velocity_joint_velocity_controller/joints/panda_joint7_controller/pid/p: 0.05
 * /panda_simulator/velocity_joint_velocity_controller/topic: /panda_simulator/...
 * /panda_simulator/velocity_joint_velocity_controller/type: panda_sim_control...
 * /ridgeback_joint_publisher/publish_rate: 50
 * /ridgeback_joint_publisher/type: joint_state_contr...
 * /ridgeback_velocity_controller/angular/z/has_acceleration_limits: True
 * /ridgeback_velocity_controller/angular/z/has_velocity_limits: True
 * /ridgeback_velocity_controller/angular/z/max_acceleration: 1.0
 * /ridgeback_velocity_controller/angular/z/max_velocity: 2.0
 * /ridgeback_velocity_controller/back_left_wheel_joint: rear_left_wheel
 * /ridgeback_velocity_controller/back_right_wheel_joint: rear_right_wheel
 * /ridgeback_velocity_controller/cmd_vel_timeout: 0.25
 * /ridgeback_velocity_controller/enable_odom_tf: False
 * /ridgeback_velocity_controller/front_left_wheel_joint: front_left_wheel
 * /ridgeback_velocity_controller/front_right_wheel_joint: front_right_wheel
 * /ridgeback_velocity_controller/linear/x/has_acceleration_limits: True
 * /ridgeback_velocity_controller/linear/x/has_velocity_limits: True
 * /ridgeback_velocity_controller/linear/x/max_acceleration: 2.5
 * /ridgeback_velocity_controller/linear/x/max_velocity: 1.1
 * /ridgeback_velocity_controller/linear/y/has_acceleration_limits: True
 * /ridgeback_velocity_controller/linear/y/has_velocity_limits: True
 * /ridgeback_velocity_controller/linear/y/max_acceleration: 2.5
 * /ridgeback_velocity_controller/linear/y/max_velocity: 1.1
 * /ridgeback_velocity_controller/pose_covariance_diagonal: [0.001, 0.001, 10...
 * /ridgeback_velocity_controller/publish_rate: 50
 * /ridgeback_velocity_controller/twist_covariance_diagonal: [0.001, 0.001, 0....
 * /ridgeback_velocity_controller/type: mecanum_drive_con...
 * /ridgeback_velocity_controller/wheel_radius_multiplier: 1.0
 * /ridgeback_velocity_controller/wheel_separation_multiplier: 1.0
 * /ridgeback_velocity_controller/wheel_separation_x: 0.638
 * /ridgeback_velocity_controller/wheel_separation_y: 0.551
 * /robot_config/arm_id: panda
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint1: 15.0
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint2: 7.5
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint3: 10.0
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint4: 12.5
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint5: 15.0
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint6: 20.0
 * /robot_config/joint_config/joint_acceleration_limit/panda_joint7: 20.0
 * /robot_config/joint_config/joint_effort_limit/panda_joint1: 87
 * /robot_config/joint_config/joint_effort_limit/panda_joint2: 87
 * /robot_config/joint_config/joint_effort_limit/panda_joint3: 87
 * /robot_config/joint_config/joint_effort_limit/panda_joint4: 87
 * /robot_config/joint_config/joint_effort_limit/panda_joint5: 12
 * /robot_config/joint_config/joint_effort_limit/panda_joint6: 12
 * /robot_config/joint_config/joint_effort_limit/panda_joint7: 12
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint1: -2.8973
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint2: -1.7628
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint3: -2.8973
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint4: -3.0718
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint5: -2.8973
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint6: -0.0175
 * /robot_config/joint_config/joint_position_limit/lower/panda_joint7: -2.8973
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint1: 2.8973
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint2: 1.7628
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint3: 2.8973
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint4: -0.0698
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint5: 2.8973
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint6: 3.7525
 * /robot_config/joint_config/joint_position_limit/upper/panda_joint7: 2.8973
 * /robot_config/joint_config/joint_velocity_limit/panda_joint1: 2.175
 * /robot_config/joint_config/joint_velocity_limit/panda_joint2: 2.175
 * /robot_config/joint_config/joint_velocity_limit/panda_joint3: 2.175
 * /robot_config/joint_config/joint_velocity_limit/panda_joint4: 2.175
 * /robot_config/joint_config/joint_velocity_limit/panda_joint5: 2.61
 * /robot_config/joint_config/joint_velocity_limit/panda_joint6: 2.61
 * /robot_config/joint_config/joint_velocity_limit/panda_joint7: 2.61
 * /robot_config/joint_names: ['panda_joint1', ...
 * /robot_config/neutral_pose/panda_joint1: -0.01779206022777...
 * /robot_config/neutral_pose/panda_joint2: -0.7601235411041661
 * /robot_config/neutral_pose/panda_joint3: 0.019782607023391807
 * /robot_config/neutral_pose/panda_joint4: -2.342050140544315
 * /robot_config/neutral_pose/panda_joint5: 0.029840531355804868
 * /robot_config/neutral_pose/panda_joint6: 1.5411935298621688
 * /robot_config/neutral_pose/panda_joint7: 0.7534486589746342
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.15.13
 * /twist_marker_server/linear_scale/x: 1
 * /twist_marker_server/linear_scale/y: 1
 * /twist_marker_server/max_negative_linear_velocity/x: -1
 * /twist_marker_server/max_negative_linear_velocity/y: -1
 * /twist_marker_server/max_positive_linear_velocity/x: 1
 * /twist_marker_server/max_positive_linear_velocity/y: 1
 * /use_sim_time: True

NODES
  /
    cmd_vel_relay (topic_tools/relay)
    controller_spawner_on (controller_manager/controller_manager)
    controller_spawner_stopped (controller_manager/controller_manager)
    ekf_localization (robot_localization/ekf_localization_node)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    joint_trajectory_server_emulator (panda_sim_custom_action_server/start_joint_trajectory_server.py)
    mbs_rp_controller_spawner (controller_manager/spawner)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    startup_script (panda_gazebo/force_neutral_pose.py)
    topic_remap (topic_tools/relay)
    twist_marker_server (interactive_marker_twist_server/marker_server)
    urdf_spawner (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [67740]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ad088a06-6d59-11ec-9d30-3d63d0be0631
process[rosout-1]: started with pid [67790]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [67798]
process[gazebo-3]: started with pid [67799]
process[gazebo_gui-4]: started with pid [67804]
process[urdf_spawner-5]: started with pid [67815]
process[ekf_localization-6]: started with pid [67818]
process[cmd_vel_relay-7]: started with pid [67822]
process[twist_marker_server-8]: started with pid [67827]
process[mbs_rp_controller_spawner-9]: started with pid [67832]
process[controller_spawner_on-10]: started with pid [67837]
process[controller_spawner_stopped-11]: started with pid [67841]
process[topic_remap-12]: started with pid [67842]
process[joint_trajectory_server_emulator-13]: started with pid [67845]
process[startup_script-14]: started with pid [67848]
[INFO] [1641299249.645095, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1641299249.925514704]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1641299249.929125832]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1641299250.185857356]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1641299250.187111066]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1641299250.810984731]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ERROR] [1641299250.985350, 2761.727000]: Spawn service failed. Exiting.
[ INFO] [1641299250.994471444, 2761.727000000]: Physics dynamic reconfigure ready.
Warning [Model.cc:212] Non-unique names detected in XML children of model with name[ridgeback].
[ INFO] [1641299251.565410133, 2761.727000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1641299251.565507167, 2761.727000000]: Starting Laser Plugin (ns = /)
[ INFO] [1641299251.566932102, 2761.727000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[urdf_spawner-5] process has died [pid 67815, exit code 1, cmd /opt/ros/noetic/lib/gazebo_ros/spawn_model -urdf -model ridgeback -param robot_description -x 0 -y 0 -z 0.1 -Y 0 __name:=urdf_spawner __log:=/home/mbs/.ros/log/ad088a06-6d59-11ec-9d30-3d63d0be0631/urdf_spawner-5.log].
log file: /home/mbs/.ros/log/ad088a06-6d59-11ec-9d30-3d63d0be0631/urdf_spawner-5*.log
[ INFO] [1641299251.817883880, 2761.727000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1641299251.817951213, 2761.727000000]: Starting Laser Plugin (ns = /)
[ INFO] [1641299251.819309282, 2761.727000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1641299262.906477929, 2761.727000000]: Ouster laser plugin ready, 64 lasers
[ INFO] [1641299263.044380555, 2761.727000000]: Loading gazebo_ros_control plugin
[ INFO] [1641299263.044501736, 2761.727000000]: Starting gazebo_ros_control plugin in namespace: /
[ INFO] [1641299263.045210666, 2761.727000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [robot_description] on the ROS param server.
[ERROR] [1641299263.234443768, 2761.727000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/mbs_lift_joint
[ERROR] [1641299263.235332415, 2761.727000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/linear_holder_2_joint
[ INFO] [1641299263.245676874, 2761.727000000]: Loaded gazebo_ros_control.
[ INFO] [1641299263.256263761, 2761.727000000]: ForceBasedMove using gains: yaw: 500 x: 10000 y: 10000

[ INFO] [1641299263.256328763, 2761.727000000]: robotBaseFrame for force based move plugin: base_link

[ INFO] [1641299263.314986041, 2761.727000000]: GazeboRosJointStatePublisher is going to publish joint: front_rocker
[ INFO] [1641299263.315040849, 2761.727000000]: Starting GazeboRosJointStatePublisher Plugin (ns = //)!, parent name: ridgeback
[ INFO] [1641299263.360212453, 2761.727000000]: ft_sensor plugin reporting wrench values to the frame [panda_link7]
[ INFO] [1641299263.360264654, 2761.727000000]: imu plugin missing <gaussianNoise>, defaults to 0.0
[ INFO] [1641299263.361487442, 2761.727000000]: Loading gazebo_ros_control plugin
[ INFO] [1641299263.361528743, 2761.727000000]: Starting gazebo_ros_control plugin in namespace: /
[ERROR] [1641299263.456742203, 2761.727000000]: This controller requires a hardware interface of type 'panda_hardware_interface::SharedJointInterface'. Make sure this is registered in the hardware_interface::RobotHW class.
[ERROR] [1641299263.456812231, 2761.727000000]: Initializing controller 'panda_simulator/velocity_joint_velocity_controller' failed
Error when loading 'panda_simulator/velocity_joint_velocity_controller'
[ERROR] [1641299263.463295908, 2761.727000000]: This controller requires a hardware interface of type 'panda_hardware_interface::SharedJointInterface'. Make sure this is registered in the hardware_interface::RobotHW class.
[ERROR] [1641299263.463361024, 2761.727000000]: Initializing controller 'panda_simulator/effort_joint_gravity_controller' failed
Error when loading 'panda_simulator/effort_joint_gravity_controller'
[ERROR] [1641299263.464990698, 2761.727000000]: This controller requires a hardware interface of type 'panda_hardware_interface::SharedJointInterface'. Make sure this is registered in the hardware_interface::RobotHW class.
[ERROR] [1641299263.465062841, 2761.727000000]: Initializing controller 'panda_simulator/position_joint_position_controller' failed
Error when loading 'panda_simulator/position_joint_position_controller'
[ERROR] [1641299263.473306586, 2761.727000000]: This controller requires a hardware interface of type 'panda_hardware_interface::SharedJointInterface'. Make sure this is registered in the hardware_interface::RobotHW class.
[ERROR] [1641299263.473404307, 2761.727000000]: Initializing controller 'panda_simulator/effort_joint_torque_controller' failed
Error when loading 'panda_simulator/effort_joint_torque_controller'
Loaded 'panda_simulator/joint_state_controller'
[ERROR] [1641299263.479318364, 2761.727000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/front_left_wheel/set_parameters]
[ERROR] [1641299263.485746011, 2761.727000000]: Could not start controller with name 'panda_simulator/position_joint_position_controller' because no controller with this name exists
Error when starting ['panda_simulator/position_joint_position_controller'] and stopping []
[ERROR] [1641299263.504702191, 2761.727000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/front_right_wheel/set_parameters]
[INFO] [1641299263.513402, 2761.727000]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1641299263.518311, 2761.727000]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1641299263.526630, 2761.727000]: Loading controller: ridgeback_joint_publisher
[ERROR] [1641299263.536651750, 2761.727000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/rear_left_wheel/set_parameters]
[ERROR] [1641299263.566932359, 2761.727000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/rear_right_wheel/set_parameters]
[ERROR] [1641299263.583248855, 2761.727000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/mbs_lift_joint
[ERROR] [1641299263.583873172, 2761.727000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/linear_holder_2_joint
[ERROR] [1641299263.587554460, 2761.727000000]: Tried to advertise a service that is already advertised in this node [/controller_manager/list_controllers]
[ERROR] [1641299263.587604864, 2761.727000000]: Tried to advertise a service that is already advertised in this node [/controller_manager/list_controller_types]
[ERROR] [1641299263.587642437, 2761.727000000]: Tried to advertise a service that is already advertised in this node [/controller_manager/load_controller]
[ERROR] [1641299263.587664830, 2761.727000000]: Tried to advertise a service that is already advertised in this node [/controller_manager/unload_controller]
[ERROR] [1641299263.587684241, 2761.727000000]: Tried to advertise a service that is already advertised in this node [/controller_manager/switch_controller]
[ERROR] [1641299263.587707700, 2761.727000000]: Tried to advertise a service that is already advertised in this node [/controller_manager/reload_controller_libraries]
[ INFO] [1641299263.587824891, 2761.727000000]: Loaded gazebo_ros_control.
[ WARN] [1641299263.590560869, 2761.728000000]: Failed to meet update rate! Took 2761.7280000000000655
Started ['panda_simulator/joint_state_controller'] successfully
[INFO] [1641299263.602101, 2761.734000]: Loading controller: ridgeback_velocity_controller
[ WARN] [1641299263.602784975, 2761.734000000]: Failed to meet update rate! Took 2761.7139999999999418
[ INFO] [1641299263.640094388, 2761.764000000]: Use the roller's radius rather than the wheel's: 0.
[ INFO] [1641299263.641205950, 2761.764000000]: Front left wheel joint (wheel0) is : front_left_wheel
[ INFO] [1641299263.644633614, 2761.767000000]: Back left wheel joint (wheel1) is : rear_left_wheel
[ INFO] [1641299263.646709175, 2761.767000000]: Back right wheel joint (wheel2) is : rear_right_wheel
[ INFO] [1641299263.647773663, 2761.768000000]: Front right wheel joint (wheel3) is : front_right_wheel
[ INFO] [1641299263.651165529, 2761.770000000]: Controller state will be published at 50Hz.
[ INFO] [1641299263.655435667, 2761.772000000]: Velocity commands will be considered old if they are older than 0.25s.
[ INFO] [1641299263.656221874, 2761.772000000]: Base frame_id set to base_link
[ INFO] [1641299263.656776631, 2761.772000000]: Odom frame_id set to odom
[ INFO] [1641299263.657741380, 2761.773000000]: Publishing to tf is disabled
[ INFO] [1641299263.684443623, 2761.795000000]: Wheel seperation in X: 0.638
[ INFO] [1641299263.684563652, 2761.795000000]: Wheel seperation in Y: 0.551
[ INFO] [1641299263.685940923, 2761.796000000]: Wheel radius: 0.0759
[INFO] [1641299263.705791, 2761.813000]: Loading controller: lift_joint_state_controller
[INFO] [1641299263.719097, 2761.815000]: Loading controller: lift_joint_position_controller
[INFO] [1641299263.750322, 2761.843000]: Controller Spawner: Loaded controllers: ridgeback_joint_publisher, ridgeback_velocity_controller, lift_joint_state_controller, lift_joint_position_controller
[INFO] [1641299263.758152, 2761.849000]: Started controllers: ridgeback_joint_publisher, ridgeback_velocity_controller, lift_joint_state_controller, lift_joint_position_controller
Traceback (most recent call last):
  File "/home/mbs/mbs_dev/mbs_ws/workspaces/mbs_rp_ws/devel/lib/panda_sim_custom_action_server/start_joint_trajectory_server.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/mbs/mbs_dev/mbs_ws/workspaces/mbs_rp_ws/src/thirdy_party/franka_simulator/panda_simulator/panda_sim_custom_action_server/scripts/start_joint_trajectory_server.py", line 83, in <module>
    main()
  File "/home/mbs/mbs_dev/mbs_ws/workspaces/mbs_rp_ws/src/thirdy_party/franka_simulator/panda_simulator/panda_sim_custom_action_server/scripts/start_joint_trajectory_server.py", line 79, in main
    start_server(args.rate)
  File "/home/mbs/mbs_dev/mbs_ws/workspaces/mbs_rp_ws/src/thirdy_party/franka_simulator/panda_simulator/panda_sim_custom_action_server/scripts/start_joint_trajectory_server.py", line 56, in start_server
    jtas.append(JointTrajectoryActionServer(dyn_cfg_srv, rate))
  File "/home/mbs/mbs_dev/mbs_ws/workspaces/mbs_rp_ws/src/thirdy_party/franka_simulator/panda_simulator/panda_sim_custom_action_server/src/panda_sim_custom_action_server/joint_trajectory_action_server.py", line 170, in __init__
    self._arm = franka_interface.ArmInterface(synchronous_pub=True)
  File "/home/mbs/mbs_dev/mbs_ws/workspaces/mbs_rp_ws/src/thirdy_party/franka_simulator/franka_ros_interface/franka_interface/src/franka_interface/arm.py", line 213, in __init__
    franka_dataflow.wait_for(lambda: len(list(self._joint_angle.keys())) > 0,
  File "/home/mbs/mbs_dev/mbs_ws/workspaces/mbs_rp_ws/src/thirdy_party/franka_simulator/franka_ros_interface/franka_interface/src/franka_dataflow/wait_for.py", line 56, in wait_for
    raise OSError(errno.ETIMEDOUT, timeout_msg)
TimeoutError: [Errno 110] Panda arm init failed to get current joint_states from /panda_simulator/custom_franka_state_controller/joint_states
[controller_spawner_stopped-11] process has finished cleanly
log file: /home/mbs/.ros/log/ad088a06-6d59-11ec-9d30-3d63d0be0631/controller_spawner_stopped-11*.log
[controller_spawner_on-10] process has finished cleanly
log file: /home/mbs/.ros/log/ad088a06-6d59-11ec-9d30-3d63d0be0631/controller_spawner_on-10*.log
[startup_script-14] process has finished cleanly
log file: /home/mbs/.ros/log/ad088a06-6d59-11ec-9d30-3d63d0be0631/startup_script-14*.log
^C[joint_trajectory_server_emulator-13] killing on exit
[topic_remap-12] killing on exit
[mbs_rp_controller_spawner-9] killing on exit
[twist_marker_server-8] killing on exit
[cmd_vel_relay-7] killing on exit
[ekf_localization-6] killing on exit
[gazebo_gui-4] killing on exit
[gazebo-3] killing on exit
[robot_state_publisher-2] killing on exit
[INFO] [1641299342.029502, 2828.945000]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1641299342.031701, 2828.945000]: Stopping all controllers...
[gazebo_gui-4] escalating to SIGTERM
[mbs_rp_controller_spawner-9] escalating to SIGTERM
[gazebo-3] escalating to SIGTERM
[WARN] [1641299357.227320, 2828.951000]: Controller Spawner error while taking down controllers: transport error completing service call: unable to receive data from sender, check sender's logs for details
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

I really am not able to understand where the problem is coming from, any leads on solving the problem will highly be appreciated. Thank you so much in advance.

**Comment by RENFAN0706** [comment]
Hi,I have met the same problem.Have you solved it?
